[project]
name = 'Blockchain-Based-Renewable-Energy-Grid-Integration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.generator-verification]
path = 'contracts/generator-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.grid-stability]
path = 'contracts/grid-stability.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-forecasting]
path = 'contracts/production-forecasting.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage-coordination]
path = 'contracts/storage-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
